# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MaintenanceObject')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MaintenanceType')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancelink',
            name='maintenance_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.MaintenanceObject'),
        ),
        migrations.AddField(
            model_name='maintenancelink',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.MaintenanceType'),
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='maintenance_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MaintenanceObject'),
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MaintenanceType'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenancelink',
            unique_together=set([('maintenance_object', 'maintenance_type')]),
        ),
    ]
